language: python
      
python:
  - 3.5
  - 3.6
  - 3.7

env:
  matrix:
  - DJANGO='django111' CMS='cms35'
  - DJANGO='django111' CMS='cms36'
  - DJANGO='django20' CMS='cms36'
  - DJANGO='django21' CMS='cms36'
  - DJANGO='django22' CMS='cms37'

install:
  - pip install tox

script:
  - tox -e "$PYVER-$DJANGO-$CMS"
