language: python
      
python:
  - 3.5
  - 3.6
  - 3.7

env:
  matrix:
  - DJANGOVER=django111 CMSVER=cms35
  - DJANGOVER=django111 CMSVER=cms36
  - DJANGOVER=django20 CMSVER=cms36
  - DJANGOVER=django21 CMSVER=cms36
  - DJANGOVER=django22 CMSVER=cms37

install:
  - pip install tox

script:
  - export TOX_ENV=py${TRAVIS_PYTHON_VERSION/./}-${DJANGOVER}-${CMSVER}
  - tox -e "$TOX_ENV"
