name: Test djangocms-cascade

on:
  push:
    branches: [ "main", "releases/*" ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        django-version: ["3.1", "3.2"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade PIP
      run: python -m pip install --upgrade pip
    - name: Install Django-3.1
      if: matrix.django-version == '3.1'
      run: python -m pip install "Django<3.2"
    - name: Install Django-3.2
      if: matrix.django-version == '3.2'
      run: python -m pip install "Django<4.0"
    - name: Install Django-4.0
      if: matrix.django-version == '4.0'
      run: |
        python -m pip install "Django<4.1"
        python -m pip install "django-admin-sortable>=2.0"
    - name: Install dependencies
      run: |
        pip install -r requirements/base.txt
        pip install -r tests/requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --ignore=F821 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        python -m pytest tests
